name: Link, test and build
jobs:
  run-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - name: vot lint
      run: npx eslint ./src
    - name: teper test
      run: npm test
    - name: teper build
      run: npm run build