name: Link, test and build
on: push
jobs:
  build222:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: vot install
          run: npm ci
        - name: vot lint
          run: npx eslint ./src
        - name: teper test
          run: npm test
        - name: teper build
          run: npm run build