name: Lint, test, build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: npm install
      - name: Lint
        run: npx eslint ./src
      - name: test
        run: npm test
      - name: build
        run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: build-dir
          path: ./build
      - uses: actions/download-artifact@v3
        with:
          name: build-dir
          
      - name: Display structure of downloaded files
        run: ls -R
  

  