name: My Workflow

on: push

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: github
        run: ${{ github }}
      - name: secrets
        run: ${{ secrets }}
      - name: matrix
        run: ${{ matrix }}
      - name: steps
        run: ${{ steps }}
      - name: env
        run: ${{ env }}
      - name: outputs
        run: ${{ outputs }}
        