name: My Workflow

on: push

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: ls
      - name: pwd
        run: pwd
      - name: change dir
        run: cd /home
      - name: ls after change dir
        run: ls
        