name: Lint, test, build
on: push
env:
  VARIABLE_1: $VARIABLE_1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: dumb branch
        run: echo ${{ github.ref }}
      - name: echo VARIABLE_1
        run: echo $VARIABLE_1
      - name: echo SECRET_1
        run: echo ${{ secrets.SECRET_1 }}
      - name: install dependencies
        run: npm ci
      - name: Lint
        run: npx eslint ./src
      - name: test
        run: npm test
      - name: build
        run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: build-dir
          path: ./build
          retention-days: 10
      - uses: actions/download-artifact@v3
        with:
          name: build-dir
          
      - name: Display structure of downloaded files
        run: ls -R
  

  